### ISSUE TITLE
Broken build for 2.7 / 3.7

### ISSUE THREAD

**Issue by MartinThoma** [Teemu/pytest-sugar#209]
The [Travis build](https://travis-ci.org/github/Teemu/pytest-sugar) is broken at the moment for 2.7 and 3.7. While I would drop the 2.7 support completely, it is interesting that 3.7 fails and 3.4 / 3.5 / 3.6 succeeds.

It's the `TestTerminalReporter.test_xdist` and `TestTerminalReporter.test_xdist_verbose` tests. Sadly, I have no clue what the issue is in there.

This one should be fixed before #208

**Comment by Teemu** [comment]
I merged a PR that fixes the CI

**Comment by MartinThoma** [comment]
Two 3.7 and one 3.8 build are still failing: https://travis-ci.org/github/Teemu/pytest-sugar

**Comment by Teemu** [comment]
Yeah I noticed 😟
