### ISSUE TITLE
PytestRemovedIn8Warning for py.path.local

### ISSUE THREAD

**Issue by AngellusMortis** [Teemu/pytest-sugar#232]
Started getting this in my test runs after upgrading pytest. Looks like it is something that will need to be fixed before pytest==8.

Link referenced in deprecation warning: https://docs.pytest.org/en/latest/deprecations.html#py-path-local-arguments-for-hooks-replaced-with-pathlib-path

```
pytest_sugar.py:250: PytestRemovedIn8Warning: The (startdir: py.path.local) argument is deprecated, please use (start_path: pathlib.Path)
see https://docs.pytest.org/en/latest/deprecations.html#py-path-local-arguments-for-hooks-replaced-with-pathlib-path
  lines = self.config.hook.pytest_report_header(
```

**Comment by Teemu** [comment]
I think this is fixed afaik

**Comment by suutari-ai** [comment]
This is not fixed actually. I have a fix for this, so creating a PR...
